version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: Qrcode-db
    environment:
      POSTGRES_DB: Qrcode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - qrcode-network
    restart: unless-stopped

  backend:
    build: .
    container_name: Qrcode-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/Qrcode
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - qrcode-network
    restart: unless-stopped

networks:
  qrcode-network:
    driver: bridge

volumes:
  postgres-data: